Vagrant.configure("2") do |config|
    config.vm.define "gnet_web", primary: true do |gnet_web|
        gnet_web.vm.box = "ubuntu/xenial64"
        gnet_web.vm.hostname = "gnet-web"
        gnet_web.vm.synced_folder ".", "/vagrant", disabled: false, type: "rsync", rsync__exclude: [".git/"], rsync__auto: true

        gnet_web.vm.provider "virtualbox" do |vb|
            vb.name = "GNet - Web"
            vb.memory = "1024"
            vb.cpus = "2"
            vb.linked_clone = true if Gem::Version.new(Vagrant::VERSION) >= Gem::Version.new('1.8.0')
        end
        
        gnet_web.vm.network "public_network", bridge: "wlan0"
        gnet_web.vm.network "private_network", ip: "192.168.0.20"
        
        gnet_web.vm.provision "shell", path: "ProvisionScripts/web.sh"
    end
end