Vagrant.configure("2") do |config|
    config.vm.define "web" do | web | 
        web.vm.box      = "debian/jessie64"
        web.vm.hostname = "jerson-martinez-web"
        
        web.vm.provider "virtualbox" do |vb|
            vb.memory = "1024"
            vb.cpus = "2"

            vb.linked_clone = true
        end

        web.vm.network "public_network", bridge: "wlan0"
        web.vm.network "private_network", ip: "10.0.100.101"
    end

    config.vm.define "db" do | db | 
        db.vm.box       = "debian/jessie64"
        db.vm.hostname  = "jerson-martinez-db"

        db.vm.provider "virtualbox" do |vb|
            vb.memory = "512"
            vb.cpus = "2"

            vb.linked_clone = true
        end

        db.vm.network "private_network", ip: "10.0.100.102"
    end
end