Vagrant.configure("2") do |config|
    config.vm.box = "debian/jessie64"
    config.vm.hostname = "jerson-martinez"
    config.vm.network "forwarded_port", guest: 80, host: 8080

    config.vm.provider "virtualbox" do | vb |
        vb.name = "ForwardedPort"
        vb.memory = "512"
        vb.cpus = "2"
        vb.linked_clone = true
    end
end