Vagrant.configure("2") do |config|
    config.vm.box = "debian/jessie64"
    config.vm.hostname = "jerson-martinez"

    config.vm.network "private_network", ip: "192.168.33.10"

    config.vm.synced_folder ".", "/vagrant", type: "smb"
    #config.vm.synced_folder ".", "/vagrant", type: "nfs"
    #Ask for a password.

    config.vm.provider "virtualbox" do |vb|
        vb.memory = "512"
        vb.cpus = "2"

        vb.linked_clone = true
    end
end