Vagrant.configure("2") do |config|
    config.vm.box = "debian/jessie64"
    config.vm.hostname = "jerson-martinez"

    # config.vm.network "forwarded_port", guest: 80, host: 8080
    config.vm.network "private_network", ip: "192.168.40.10"
    config.vm.synced_folder ".", "/vagrant", type: "rsync"

    config.vm.provider "virtualbox" do |vb|
        vb.name = "WebServerNGinx"
        vb.memory = "1024"
        vb.cpus = "2"
        
        vb.linked_clone = true
    end

    config.vm.provision "shell", inline: <<-SHELL
        sudo apt-get update
        sudo apt-get install -y nginx
        sed -i 's,/var/www/html,/vagrant/nunu,g' /etc/nginx/sites-enabled/default
        sudo service nginx restart
    SHELL

end