Vagrant.configure("2") do |config|
    config.vm.box = "debian/jessie64"
    config.vm.hostname = "jerson-martinez"

    config.vm.provider "virtualbox" do |vb|
        vb.linked_clone = true
    end

    config.vm.provision "shell", path: "update.sh"
end
