Vagrant.configure("2") do |config|
    config.vm.box = "debian/jessie64"
    config.vm.hostname = "jerson-martinez"
    
    config.vm.network "public_network", bridge: "wlan0"

    config.vm.provider "virtualbox" do | vb |
        vb.name = "private_network"
        vb.memory = "512"
        vb.cpus = "2"

        vb.linked_clone = true
    end  

end
