Vagrant.configure("2") do |config|

    config.vm.define "gnet_db", primary: true do |gnet_db|
        gnet_db.vm.box = "ubuntu/xenial64"
        gnet_db.vm.hostname = "gnet-db"
    
        gnet_db.vm.provider "virtualbox" do |vb|
            vb.name = "GNet - DB"
            vb.memory = "512"
            vb.cpus = "2"
            vb.linked_clone = true if Gem::Version.new(Vagrant::VERSION) >= Gem::Version.new('1.8.0')
        end

        gnet_db.vm.network "private_network", ip: "192.168.0.10"
        gnet_db.vm.provision "shell", path: "ProvisionScripts/db.sh"
    end

    config.vm.define "gnet_web" do |gnet_web|
        gnet_web.vm.box = "ubuntu/xenial64"
        gnet_web.vm.hostname = "gnet-web"
        gnet_web.vm.synced_folder ".", "/vagrant", type: "rsync"

        gnet_web.vm.provider "virtualbox" do |vb|
            vb.name = "GNet - Web"
            vb.memory = "1024"
            vb.cpus = "2"
            vb.linked_clone = true if Gem::Version.new(Vagrant::VERSION) >= Gem::Version.new('1.8.0')
        end
        
        gnet_web.vm.network "public_network", bridge: "wlan0"
        gnet_web.vm.network "private_network", ip: "192.168.0.20"
        
        gnet_web.vm.provision "shell", path: "ProvisionScripts/web.sh"
    end

    config.vm.define "gnet_dns" do |gnet_dns|
        gnet_dns.vm.box = "ubuntu/xenial64"
        gnet_dns.vm.hostname = "gnet-dns"

        gnet_dns.vm.provider "virtualbox" do |vb|
            vb.name = "GNet - DNS"
            vb.memory = "512"
            vb.cpus = "2"
            vb.linked_clone = true if Gem::Version.new(Vagrant::VERSION) >= Gem::Version.new('1.8.0')
        end
        
        gnet_dns.vm.network "public_network", bridge: "wlan0"
        gnet_dns.vm.network "private_network", ip: "192.168.0.30"
        
        gnet_dns.vm.provision "shell", path: "ProvisionScripts/dns.sh"
    end
end