Vagrant.configure("2") do |config|
  	config.vm.box = "debian/jessie64"
  	config.vm.hostname = "jerson-martinez"

  	config.vm.provider "virtualbox" do | vb |
  		vb.name = "ConfigBasicDebian"
  		vb.memory = "512"
  		vb.cpus = "2"
  	end
end