Vagrant.configure("2") do |config|
    config.vm.box = "debian/jessie64"
    config.vm.hostname = "jerson-martinez"
  
    config.vm.synced_folder ".", "/vagrant"

    config.vm.provider "virtualbox" do |vb|
        vb.memory = "512"
        vb.cpus = "2"

        vb.linked_clone = true
    end
end