Vagrant.configure("2") do |config|
    config.vm.box = "debian/jessie64"
    
    config.persistent_storage.enabled       = true
    config.persistent_storage.location      = "tmp/disk.vdi"
    config.persistent_storage.size          = 5000
    config.persistent_storage.mountname     = 'mysql'
    config.persistent_storage.filesystem    = 'ext4'
    config.persistent_storage.mountpoint    = '/var/lib/mysql'
    config.persistent_storage.volgroupname  = 'myvolgroup'
end