Vagrant.configure("2") do |config|
    config.vm.define "controller" do |controller|
        controller.vm.box = "ubuntu/xenial64"
        controller.vm.hostname = "controller-jerson-martinez"
        controller.vm.network "private_network", ip: "192.168.33.10"
        controller.vm.synced_folder ".", "/vagrant", type: "rsync"

        controller.vm.provider "virtualbox" do |vb|
            vb.name = "Ansible-Controller"
            vb.memory = "1024"
            vb.cpus = "2"
            vb.linked_clone = true
        end

        controller.vm.provision "shell", path: "provision.sh"
    end

    config.vm.define "node" do |node|
        node.vm.box = "ubuntu/xenial64"
        node.vm.hostname = "node-jerson-martinez"
        node.vm.network "private_network", ip: "192.168.33.11"
        node.vm.synced_folder ".", "/vagrant", type: "rsync"

        node.vm.provider "virtualbox" do |vb|
            vb.name = "Ansible-Node"
            vb.memory = "1024"
            vb.cpus = "2"
            vb.linked_clone = true
        end
    end
end