Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/xenial64"
    config.vm.hostname = "jerson-martinez"

    config.vm.network "private_network", ip: "192.168.33.10"
    config.vm.synced_folder ".", "/vagrant", type: "rsync"

    config.vm.provider "virtualbox" do |vb|
        vb.name = "Install-Ansible"
        vb.memory = "1024"
        vb.cpus = "2"

        vb.linked_clone = true
    end

    config.vm.provision "shell", path: "provision.sh"
end